/// <reference lib="webworker" />

import { precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { clientsClaim } from 'workbox-core';

declare let self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: Array<string | {
    url: string;
    revision?: string | null;
    integrity?: string;
  }>;
};

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Clean up old caches
cleanupOutdatedCaches();
clientsClaim();

// Setup navigation route to serve index.html for SPA client-side routing,
// but exclude requests containing update query params (__traffio_update)
// to prevent "a redirected response was used for a request whose redirect mode is not 'follow'" errors.
try {
  const handler = createHandlerBoundToURL('/index.html');
  const navigationRoute = new NavigationRoute(handler, {
    denylist: [
      /\?.*__traffio_update=/,
      /app-version\.json/
    ]
  });
  registerRoute(navigationRoute);
} catch (e) {
  console.error('[SW] Failed to register navigation route:', e);
}

// Listen to SKIP_WAITING message to activate the new SW immediately
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// -- PUSH NOTIFICATIONS HANDLERS (Merged from public/sw.js) --
self.addEventListener('push', function(event) {
  if (event.data) {
    try {
      const data = event.data.json();
      const options = {
        body: data.body,
        icon: data.icon || '/logo192.png',
        badge: '/badge.png',
        data: data.data,
        vibrate: [200, 100, 200],
        actions: [
          { action: 'open', title: 'Ver Mensagem' }
        ]
      };

      event.waitUntil(
        self.registration.showNotification(data.title, options)
      );
    } catch (e) {
      console.error('[SW] Error handling push event:', e);
    }
  }
});

self.addEventListener('notificationclick', function(event) {
  event.notification.close();

  if (event.action === 'open' || !event.action) {
    const urlToOpen = event.notification.data?.url || '/dashboard/inbox';
    
    event.waitUntil(
      self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then(function(clientList) {
        for (let i = 0; i < clientList.length; i++) {
          const client = clientList[i];
          if (client.url === urlToOpen && 'focus' in client) {
            return client.focus();
          }
        }
        if (self.clients.openWindow) {
          return self.clients.openWindow(urlToOpen);
        }
      })
    );
  }
});
