/// <reference lib="webworker" />

import { precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { clientsClaim } from 'workbox-core';

declare let self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: Array<string | {
    url: string;
    revision?: string | null;
    integrity?: string;
  }>;
};

// Force new service worker to activate immediately upon installation
self.addEventListener('install', () => {
  self.skipWaiting();
});

// Take control of all clients as soon as activated
self.addEventListener('activate', (event) => {
  event.waitUntil(
    Promise.all([
      cleanupOutdatedCaches(),
      self.clients.claim()
    ])
  );
});

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Listen to SKIP_WAITING message to activate the new SW immediately
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// -- PUSH NOTIFICATIONS HANDLERS (Merged from public/sw.js) --
self.addEventListener('push', function(event) {
  if (event.data) {
    try {
      const data = event.data.json();
      const options = {
        body: data.body,
        icon: data.icon || '/logo192.png',
        badge: '/badge.png',
        data: data.data,
        vibrate: [200, 100, 200],
        actions: [
          { action: 'open', title: 'Ver Mensagem' }
        ]
      };

      event.waitUntil(
        self.registration.showNotification(data.title, options)
      );
    } catch (e) {
      console.error('[SW] Error handling push event:', e);
    }
  }
});

self.addEventListener('notificationclick', function(event) {
  event.notification.close();

  if (event.action === 'open' || !event.action) {
    const urlToOpen = event.notification.data?.url || '/dashboard/inbox';
    
    event.waitUntil(
      self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then(function(clientList) {
        for (let i = 0; i < clientList.length; i++) {
          const client = clientList[i];
          if (client.url === urlToOpen && 'focus' in client) {
            return client.focus();
          }
        }
        if (self.clients.openWindow) {
          return self.clients.openWindow(urlToOpen);
        }
      })
    );
  }
});
